#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir
touch icf1.foam

# mkdir constant/triSurface
# cp ../geometry/*.stl constant/triSurface
# runApplication surfaceFeatureExtract
runApplication blockMesh
# runApplication snappyHexMesh -overwrite

# runApplication cartesianMesh
# runApplication foamDictionary constant/polyMesh/boundary -entry entry0/symm_side/type -set symmetry
# runApplication transformPoints -scale 0.001
# runApplication setFields
runApplication setAlphaField

runApplication  decomposePar 
runParallel renumberMesh -overwrite
runParallel $(getApplication)

#------------------------------------------------------------------------------
